import { StyleSheet } from 'react-native';
import { PALETTE } from './palette';
import { STYLES } from './globalStyles';

export const propertyDetailsStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: PALETTE.card,
  },
  scrollContainer: {
    backgroundColor: PALETTE.background,
  },
  centerContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    minHeight: 200,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: PALETTE.border,
    backgroundColor: PALETTE.card,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: PALETTE.textPrimary,
    textAlign: 'center',
    flex: 1,
    marginHorizontal: 8,
  },
  backButton: {
    padding: 8,
  },
  dropdownContainer: {
    flex: 1,
    marginHorizontal: 8,
  },
  dropdown: {
    backgroundColor: PALETTE.card,
    borderColor: PALETTE.border,
    borderWidth: 1,
  },
  dropdownText: {
    color: PALETTE.textPrimary,
  },
  pageTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: PALETTE.textPrimary,
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 16,
  },
  contentContainer: {
    paddingHorizontal: 20,
    paddingBottom: 20,
  },
  emptyText: {
    textAlign: 'center',
    color: PALETTE.textSecondary,
    fontSize: 16,
  },
  assetContainer: {
    backgroundColor: PALETTE.card,
    borderRadius: STYLES.borderRadius.small,
    borderWidth: 1,
    borderColor: PALETTE.border,
    marginBottom: 12,
    overflow: 'hidden',
  },
  assetHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
  },
  assetTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: PALETTE.textPrimary,
    flex: 1,
  },
  assetContent: {
    paddingHorizontal: 16,
    paddingBottom: 16,
  },
  contentSectionTitle: {
    fontSize: 14,
    fontWeight: '500',
    color: PALETTE.textSecondary,
    marginTop: 16,
    marginBottom: 8,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  specificationsBox: {
    backgroundColor: PALETTE.background,
    borderRadius: STYLES.borderRadius.small,
    padding: 12,
    borderWidth: 1,
    borderColor: PALETTE.border,
  },
  specPair: {
    flexDirection: 'row',
    paddingVertical: 4,
  },
  specKey: {
    fontWeight: '500',
    textTransform: 'capitalize',
    width: '40%',
    color: PALETTE.textSecondary,
  },
  specValue: {
    flex: 1,
    color: PALETTE.textPrimary,
  },
  historyItemContainer: {
    marginTop: 8,
  },
  historyEntry: {
    padding: 12,
    backgroundColor: PALETTE.card,
    borderRadius: STYLES.borderRadius.small,
    borderWidth: 1,
    borderColor: PALETTE.border,
  },
  historyHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  historyDate: {
    fontSize: 12,
    color: PALETTE.textSecondary,
  },
  historyDescription: {
    fontStyle: 'italic',
    color: PALETTE.textPrimary,
    marginTop: 8,
  },
  historyAuthor: {
    fontSize: 12,
    color: PALETTE.textSecondary,
    marginTop: 8,
    textAlign: 'right',
  },
  historySpecBox: {
    paddingTop: 12,
    paddingLeft: 12,
    borderLeftWidth: 2,
    borderLeftColor: PALETTE.border,
    marginTop: 12,
    marginLeft: 16,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContainer: {
    width: '95%',
    maxWidth: 400,
    maxHeight: '80%',
    backgroundColor: PALETTE.card,
    borderRadius: STYLES.borderRadius.medium,
    padding: 16,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: PALETTE.textPrimary,
  },
  closeButton: {
    padding: 8,
  },
  input: {
    backgroundColor: PALETTE.background,
    borderWidth: 1,
    borderColor: PALETTE.border,
    borderRadius: STYLES.borderRadius.small,
    padding: 16,
    fontSize: 16,
    marginBottom: 12,
  },
  submitButton: {
    backgroundColor: PALETTE.primary,
    borderRadius: STYLES.borderRadius.small,
    padding: 16,
    alignItems: 'center',
    marginTop: 16,
  },
  submitButtonText: {
    color: PALETTE.card,
    fontSize: 16,
    fontWeight: '600',
  },
  headerActions: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    padding: 16,
    borderTopWidth: 1,
    borderColor: PALETTE.border,
    backgroundColor: PALETTE.card,
  },
  addButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  addButtonText: {
    marginLeft: 8,
    fontSize: 16,
    fontWeight: '500',
    color: PALETTE.primary,
  },
  historySectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  addButtonSmall: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  addButtonSmallText: {
    marginLeft: 4,
    fontSize: 14,
    fontWeight: '500',
    color: PALETTE.primary,
  },
  label: {
    fontSize: 14,
    fontWeight: '500',
    color: PALETTE.textSecondary,
    marginBottom: 8,
  },
  specRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    width: '100%',
  },
  specInputKey: {
    maxWidth: 80,
    marginRight: 6,
    marginBottom: 0,
    padding: 10,
    fontSize: 14,
    minWidth: 60,
    flexShrink: 0,
  },
  specInputValue: {
    flex: 1,
    marginRight: 6,
    marginBottom: 0,
    padding: 10,
    fontSize: 12,
    minWidth: 0,
  },
  removeRowButton: {
    padding: 6,
    flexShrink: 0,
  },
  addRowButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 12,
    marginTop: 8,
  },
  addRowButtonText: {
    marginLeft: 8,
    color: PALETTE.primary,
    fontWeight: '500',
  },
  sortModeButton: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: PALETTE.primary,
    borderRadius: STYLES.borderRadius.small,
  },
  sortModeButtonText: {
    color: PALETTE.card,
    fontSize: 14,
    fontWeight: '600',
  },
  disciplineSpaceContainer: {
    marginBottom: 20,
  },
  disciplineSpaceTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: PALETTE.textPrimary,
    marginBottom: 12,
    paddingHorizontal: 4,
  },
  sortSection: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 10,
    backgroundColor: PALETTE.background,
  },
  sortLabel: {
    fontSize: 14,
    color: PALETTE.textSecondary,
    marginBottom: 8,
    fontWeight: '500',
  },
  sortToggleGroup: {
    flexDirection: 'row',
    marginBottom: 12,
    backgroundColor: PALETTE.card,
    borderRadius: STYLES.borderRadius.small,
    borderWidth: 1,
    borderColor: PALETTE.border,
    overflow: 'hidden',
  },
  sortToggleButton: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
  },
  sortToggleButtonActive: {
    backgroundColor: PALETTE.primary,
  },
  sortToggleText: {
    fontSize: 14,
    color: PALETTE.textSecondary,
    fontWeight: '600',
  },
  sortToggleTextActive: {
    color: PALETTE.card,
  },
  dropdownWrapper: {
    backgroundColor: PALETTE.card,
    borderRadius: STYLES.borderRadius.small,
    borderWidth: 1,
    borderColor: PALETTE.border,
  },
});
