import { StyleSheet } from 'react-native';
import { PALETTE } from './palette';
import { STYLES } from './globalStyles';

export const propertyRequestsStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: PALETTE.background,
  },
  centerContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: PALETTE.card,
    borderBottomWidth: 1,
    borderBottomColor: PALETTE.border,
  },
  backButton: {
    padding: 8,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: PALETTE.textPrimary,
  },
  listContent: {
    padding: 20,
    flexGrow: 1,
    overflow: 'visible',
  },
  card: {
    backgroundColor: PALETTE.card,
    borderRadius: STYLES.borderRadius.medium,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: PALETTE.border,
    overflow: 'hidden',
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    padding: 16,
  },
  cardHeaderText: {
      flex: 1,
  },
  propertyName: {
    fontSize: 18,
    fontWeight: '600',
    color: PALETTE.textPrimary,
  },
  assetName: {
      fontSize: 14,
      color: PALETTE.textSecondary,
      marginTop: 2,
  },
  descriptionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
    paddingHorizontal: 16,
    flexWrap: 'wrap',
  },
  descriptionText: {
    fontSize: 16,
    fontStyle: 'italic',
    color: PALETTE.textPrimary,
    flex: 1,
    marginRight: 8,
  },
  statusLabel: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    alignSelf: 'flex-start',
  },
  statusLabelAccepted: {
    backgroundColor: PALETTE.successBackground,
  },
  statusLabelRejected: {
    backgroundColor: PALETTE.dangerBackground,
  },
  statusLabelText: {
    fontSize: 11,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  statusLabelTextAccepted: {
    color: PALETTE.success,
  },
  statusLabelTextRejected: {
    color: PALETTE.danger,
  },
  submittedBy: {
      fontSize: 12,
      color: PALETTE.textSecondary,
      textAlign: 'right',
      paddingHorizontal: 16,
      paddingBottom: 2,
  },
  submittedDate: {
      fontSize: 12,
      color: PALETTE.textSecondary,
      textAlign: 'right',
      paddingHorizontal: 16,
      paddingBottom: 16,
  },
  expandedContent: {
      borderTopWidth: 1,
      borderColor: PALETTE.border,
      padding: 16,
  },
  detailsTitle: {
      fontSize: 14,
      fontWeight: '500',
      color: PALETTE.textSecondary,
      textTransform: 'uppercase',
      marginBottom: 8,
  },
  specificationsBox: {
    backgroundColor: PALETTE.background,
    borderRadius: STYLES.borderRadius.small,
    padding: 12,
  },
  specPair: {
    flexDirection: 'row',
    paddingVertical: 4,
  },
  specKey: {
    fontWeight: '500',
    width: '40%',
    color: PALETTE.textSecondary,
  },
  specValue: {
    flex: 1,
    color: PALETTE.textPrimary,
  },
  actionButtons: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    backgroundColor: PALETTE.background,
    padding: 12,
  },
  statusButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    marginLeft: 8,
  },
  declineButton: {
      backgroundColor: PALETTE.dangerBackground,
  },
  acceptButton: {
      backgroundColor: PALETTE.successBackground,
  },
  statusButtonText: {
    marginLeft: 6,
    fontWeight: '600',
  },
  emptyText: {
    fontSize: 16,
    color: PALETTE.textSecondary,
  },
  // Add property (QR scan) UI styles
  scanCard: {
    backgroundColor: PALETTE.card,
    borderRadius: STYLES.borderRadius.medium,
    padding: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: PALETTE.border,
  },
  scanTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: PALETTE.textPrimary,
    marginBottom: 12,
  },
  dottedBox: {
    width: '70%',
    maxWidth: 220,
    aspectRatio: 1,
    borderStyle: 'dashed',
    borderWidth: 2,
    borderColor: PALETTE.border,
    borderRadius: 8,
    backgroundColor: '#F6F6F8',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 8,
  },
  qrImage: {
    width: 88,
    height: 88,
    resizeMode: 'contain',
  },
  simulateButton: {
    marginTop: 16,
    backgroundColor: PALETTE.primary,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  simulateButtonText: {
    color: PALETTE.primaryForeground,
    fontWeight: '600',
  },
  // New styles for tradie request creation
  section: {
    marginBottom: 24,
    overflow: 'visible',
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: PALETTE.textPrimary,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  sortToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: PALETTE.background,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: PALETTE.border,
  },
  sortToggleText: {
    fontSize: 12,
    color: PALETTE.textSecondary,
    marginLeft: 4,
    fontWeight: '500',
  },
  createButton: {
    backgroundColor: PALETTE.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    marginBottom: 16,
  },
  createButtonText: {
    color: PALETTE.card,
    fontWeight: '600',
    marginLeft: 8,
  },
  requestForm: {
    backgroundColor: PALETTE.card,
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: PALETTE.border,
    overflow: 'visible',
  },
  formTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: PALETTE.textPrimary,
    marginBottom: 16,
  },
  formField: {
    marginBottom: 16,
    zIndex: 1,
  },
  formFieldActive: {
    marginBottom: 16,
    zIndex: 1000,
  },
  fieldLabel: {
    fontSize: 14,
    fontWeight: '500',
    color: PALETTE.textPrimary,
    marginBottom: 8,
  },
  formInput: {
    borderWidth: 1,
    borderColor: PALETTE.border,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 16,
    color: PALETTE.textPrimary,
    backgroundColor: PALETTE.background,
  },
  dropdownField: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: PALETTE.border,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: PALETTE.card,
  },
  dropdownText: {
    fontSize: 16,
    color: PALETTE.textPrimary,
    flex: 1,
  },
  dropdownPlaceholder: {
    color: PALETTE.textSecondary,
  },
  dropdownList: {
    position: 'absolute',
    top: '100%',
    left: 0,
    right: 0,
    backgroundColor: PALETTE.card,
    borderWidth: 1,
    borderColor: PALETTE.border,
    borderRadius: 8,
    marginTop: 4,
    maxHeight: 200,
    zIndex: 9999,
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
  },
  dropdownItem: {
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: PALETTE.border,
  },
  dropdownItemText: {
    fontSize: 16,
    color: PALETTE.textPrimary,
  },
  dateInput: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: PALETTE.border,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: PALETTE.background,
  },
  formActions: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 8,
  },
  cancelButton: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: PALETTE.border,
    backgroundColor: PALETTE.background,
    marginRight: 8,
    alignItems: 'center',
  },
  cancelButtonText: {
    color: PALETTE.textPrimary,
    fontWeight: '500',
  },
  submitButton: {
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    backgroundColor: PALETTE.primary,
    alignItems: 'center',
    minWidth: 200,
  },
  submitButtonText: {
    color: PALETTE.card,
    fontWeight: '600',
  },
  // --- ADDED STYLES FOR SPECIFICATION EDITOR ---
  input: {
    backgroundColor: PALETTE.background,
    borderWidth: 1,
    borderColor: PALETTE.border,
    borderRadius: STYLES.borderRadius.small,
    padding: 16,
    fontSize: 16,
    marginBottom: 12,
  },
  label: {
    fontSize: 14,
    fontWeight: '500',
    color: PALETTE.textSecondary,
    marginBottom: 8,
  },
  specRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    width: '100%',
  },
  specInputKey: {
    flex: 2,
    marginRight: 6,
    marginBottom: 0,
    padding: 10,
    fontSize: 14,
  },
  specInputValue: {
    flex: 3,
    marginRight: 6,
    marginBottom: 0,
    padding: 10,
    fontSize: 14,
  },
  removeRowButton: {
    padding: 6,
  },
  addRowButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 12,
    marginTop: 8,
    borderWidth: 1,
    borderColor: PALETTE.border,
    borderRadius: 8,
  },
  addRowButtonText: {
    marginLeft: 8,
    color: PALETTE.primary,
    fontWeight: '500',
  },
});
